### ISSUE TITLE
After Calcite 1.32 filter query is not working in modin-on-hdk

### ISSUE THREAD

**Issue by Egor-Krivov** [intel-ai/hdk#146]
After the commit https://github.com/intel-ai/hdk/commit/088e66a44acb8db9eedc5b5e20faad8b04617bf1 our source code using modin on HDK stopped working on function `filter_df`. Right after https://github.com/intel-ai/hdk/commit/c17e14dbf6e7978bcf87b0cb9ca1a3b8920ef6b2 it was working fine. In https://github.com/intel-ai/hdk/commit/3f40fac58eaf8d3901ca4383286bc2a25c95a957 HDK just stopped building. So the breaking change could be in 088e66a44acb8db9eedc5b5e20faad8b04617bf1 or 3f40fac58eaf8d3901ca4383286bc2a25c95a957 

Content of `filter_df` function that receives the error:
```
def filter_df(df, is_hdk_mode=True):
    """apply a list of filter conditions to throw out records with missing or outlier values"""
    # Modin_on_hdk does not support query method, but Modin_on_ray works much faster using query method
    df = df[
        (df.fare_amount > 1)
        & (df.fare_amount < 500)
        & (df.passenger_count > 0)
        & (df.passenger_count < 6)
        & (df.pickup_longitude > -75)
        & (df.pickup_longitude < -73)
        & (df.dropoff_longitude > -75)
        & (df.dropoff_longitude < -73)
        & (df.pickup_latitude > 40)
        & (df.pickup_latitude < 42)
        & (df.dropoff_latitude > 40)
        & (df.dropoff_latitude < 42)
        & (df.trip_distance > 0)
        & (df.trip_distance < 500)
        & ((df.trip_distance <= 50) | (df.fare_amount >= 50))
        & ((df.trip_distance >= 10) | (df.fare_amount <= 300))
        & (df.dropoff_datetime > df.pickup_datetime)
    ]

    df = df.reset_index(drop=True)
    trigger_execution(df)
    return df
```
trigger execution just evaluates dataframe.

Traceback:
```
Traceback (most recent call last):
21:50:59     File "run_modin_tests.py", line 142, in <module>
21:50:59       main()
21:50:59     File "run_modin_tests.py", line 138, in main
21:50:59       run_benchmark_task(args)
21:50:59     File "run_modin_tests.py", line 88, in run_benchmark_task
21:50:59       run_benchmarks(
21:50:59     File "/data/datab/tc_agent1/work/3523f86603464d1f/omniscripts/utils/utils.py", line 735, in run_benchmarks
21:50:59       benchmark_results = run_benchmark(parameters)
21:50:59     File "/data/datab/tc_agent1/work/3523f86603464d1f/omniscripts/taxi_ml/taxi_ml_benchmark.py", line 315, in run_benchmark
21:50:59       df, task2time["filter_df"] = filter_df(df, is_hdk_mode=is_hdk_mode)
21:50:59     File "/data/datab/tc_agent1/work/3523f86603464d1f/omniscripts/taxi_ml/taxi_ml_benchmark.py", line 24, in wrapper
21:50:59       res = func(*args, **kwargs)
21:50:59     File "/data/datab/tc_agent1/work/3523f86603464d1f/omniscripts/taxi_ml/taxi_ml_benchmark.py", line 186, in filter_df
21:50:59       trigger_execution(df)
21:50:59     File "/data/datab/tc_agent1/work/3523f86603464d1f/omniscripts/utils/trigger_execution.py", line 91, in trigger_execution
21:50:59       execute(df)
21:50:59     File "/data/datab/tc_agent1/work/3523f86603464d1f/omniscripts/utils/trigger_execution.py", line 49, in execute
21:50:59       df.shape
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/pandas/base.py", line 3917, in __getattribute__
21:50:59       attr = super().__getattribute__(item)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 370, in shape
21:50:59       return len(self.index), len(self.columns)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/pandas/base.py", line 3917, in __getattribute__
21:50:59       attr = super().__getattribute__(item)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/pandas/base.py", line 585, in _get_index
21:50:59       return self._query_compiler.index
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 471, in _get_index
21:50:59       return self._modin_frame.index
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1899, in _get_index
21:50:59       self._execute()
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
21:50:59       return obj(*args, **kwargs)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1685, in _execute
21:50:59       new_partitions = self._partition_mgr_cls.run_exec_plan(
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
21:50:59       return obj(*args, **kwargs)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py", line 287, in run_exec_plan
21:50:59       at = omniSession.executeRA(cmd_prefix + calcite_json)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py", line 91, in executeRA
21:50:59       return cls._executeRelAlgJson(ra)
21:50:59     File "/data/datae/teamcity/miniconda3_2/envs/hdk_test_49100/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py", line 73, in _executeRelAlgJson
21:50:59       rel_alg_executor = pyhdk.sql.RelAlgExecutor(
21:50:59     File "_sql.pyx", line 88, in pyhdk._sql.RelAlgExecutor.__cinit__
21:50:59   RuntimeError: Failed to parse relational algebra tree. Possible query syntax error.
```

**Comment by Egor-Krivov** [comment]
Duplicate of https://github.com/intel-ai/hdk/issues/145
