### ISSUE TITLE
pyhdk conda-forge release does not work for the main branch

### ISSUE THREAD

**Issue by leshikus** [intel-ai/hdk#330]
This recipe seems to work for `release/v.0.4.0` and does not work for `main`
https://github.com/leshikus/hdk-feedstock

The error message is
```
Traceback (most recent call last):
import: 'pyhdk'
  File "/home/conda/feedstock_root/build_artifacts/hdk_1680012995309/test_tmp/run_test.py", line 2, in <module>
    import pyhdk
ModuleNotFoundError: No module named 'pyhdk'
```

To check this clone the repo and run
```
$ python build-locally.py linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20python3.9.____cpython
```

**Comment by leshikus** [comment]
This works from behind a proxy. To debug this one may check `docker ps -a` for `quay.io/condaforge/linux-anvil-cos7-x86_64` container instance `id`, use `docker start $id`, then `docker exec -ti $id bash`

**Comment by kurapov-peter** [comment]
This doesn't reproduce for me. Any changes to the recipe needed?

**Comment by Garra1980** [comment]
Are you able to build locally current hdk mmain branch using existing conda-forge recipe?

**Comment by alexbaden** [comment]
This issue is reproducible running a conda build against the `meta.yml` file without `conda-forge`. It does appear to be introduced by https://github.com/intel-ai/hdk/commit/254196f3bfe28ebfc5dbc8e56274a6ae9c9f0164 -- specifically, the `--prefix` option in `python setup.py install`. The prefix should correspond to the python installation directory where we intend to install the package.

If I drop the prefix introduced in `python/CMakeLists.txt` I get missing library errors when building with `meta.yml`. 

```
ImportError: libConfigBuilder.so: cannot open shared object file: No such file or directory
```

The libraries are in the broken install package in `opt/hdk`, and the library path is set in cmake, but the test doesn't appear to find them. @ienkovich any ideas, did you encounter this when you put the cython package together initially?

**Comment by alexbaden** [comment]
```
ImportError: libConfigBuilder.so: cannot open shared object file: No such file or directory
Tests failed for pyhdk-0.4.0-py310h1234567_0_cpu.tar.bz2 - moving package to /home/abaden/miniconda3/conda-bld/broken
WARNING:conda_build.build:Tests failed for pyhdk-0.4.0-py310h1234567_0_cpu.tar.bz2 - moving package to /home/abaden/miniconda3/conda-bld/broken
export PREFIX=/home/abaden/miniconda3/conda-bld/hdk_1680238980148/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
export SRC_DIR=/home/abaden/miniconda3/conda-bld/hdk_1680238980148/test_tmp
import: 'pyhdk'
TESTS FAILED: pyhdk-0.4.0-py310h1234567_0_cpu.tar.bz2
```

**Comment by leshikus** [comment]
now I see the problem with `libConfigBuilder.so` as well

**Comment by Garra1980** [comment]
Doesn't it should be fixed after reverting https://github.com/intel-ai/hdk/commit/254196f3bfe28ebfc5dbc8e56274a6ae9c9f0164?

**Comment by Garra1980** [comment]
build-locally from main branch is fine for me

**Comment by leshikus** [comment]
build-locally works; I believe `libConfigBuilder.so` is loaded conditionally

**Comment by Garra1980** [comment]
you mean checking import pyhdk insufficient?

**Comment by leshikus** [comment]
`import pyhdk` is sufficient
```
2023-04-07T03:05:54.3086278Z -- Set runtime path of "/usr/share/miniconda/lib/libConfigBuilder.so" to ""
2023-04-07T03:05:54.3086530Z -- Installing: /usr/share/miniconda/lib/libSqliteConnector.so
2023-04-07T03:05:54.3092146Z -- Set runtime path of "/usr/share/miniconda/lib/libSqliteConnector.so" to ""
2023-04-07T03:05:54.3092461Z -- Installing: /usr/share/miniconda/lib/libResultSet.so
2023-04-07T03:05:54.3159292Z -- Set runtime path of "/usr/share/miniconda/lib/libResultSet.so" to ""
2023-04-07T03:05:54.3159623Z -- Installing: /usr/share/miniconda/lib/libResultSetRegistry.so
2023-04-07T03:05:54.3219164Z -- Set runtime path of "/usr/share/miniconda/lib/libResultSetRegistry.so" to ""
2023-04-07T03:05:54.3233740Z + python -c import pyhdk
2023-04-07T03:05:54.3399404Z Traceback (most recent call last):
2023-04-07T03:05:54.3399614Z   File "<string>", line 1, in <module>
2023-04-07T03:05:54.3400037Z   File "/usr/share/miniconda/envs/omnisci-dev/lib/python3.9/site-packages/pyhdk-0.6.0.dev0-py3.9-linux-x86_64.egg/pyhdk/__init__.py", line 17, in <module>
2023-04-07T03:05:54.3400339Z     from pyhdk._common import TypeInfo, buildConfig, initLogger
2023-04-07T03:05:54.3400575Z ImportError: libConfigBuilder.so: cannot open shared object file: No such file or directory
```

**Comment by leshikus** [comment]
the file exists and ldd shows it can be loaded correctly

```
2023-04-07T19:41:08.6240695Z + ldd /usr/share/miniconda/lib/libConfigBuilder.so
2023-04-07T19:41:08.6291725Z 	linux-vdso.so.1 (0x00007ffc66ac8000)
2023-04-07T19:41:08.6292040Z 	libboost_program_options.so.1.78.0 => /usr/share/miniconda/envs/omnisci-dev/lib/libboost_program_options.so.1.78.0 (0x00007f96466f5000)
2023-04-07T19:41:08.6292368Z 	libstdc++.so.6 => /usr/share/miniconda/envs/omnisci-dev/lib/libstdc++.so.6 (0x00007f9646541000)
2023-04-07T19:41:08.6292660Z 	libgcc_s.so.1 => /usr/share/miniconda/envs/omnisci-dev/lib/libgcc_s.so.1 (0x00007f9646528000)
2023-04-07T19:41:08.6292924Z 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f96462fe000)
2023-04-07T19:41:08.6293181Z 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f96462f7000)
2023-04-07T19:41:08.6293432Z 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9646210000)
2023-04-07T19:41:08.6293693Z 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f964620b000)
2023-04-07T19:41:08.6293951Z 	/lib64/ld-linux-x86-64.so.2 (0x00007f964676f000)
```

**Comment by leshikus** [comment]
I've tried locally, install works properly; need to understand what is different in the CI environment

**Comment by leshikus** [comment]
It turns out 
```
 cd modin && pip install -e . && pip install .[ray] ray==2.0.1
```
removed dependencies which were needed for cmake --install to work properly

**Comment by Garra1980** [comment]
> It turns out
> 
> ```
>  cd modin && pip install -e . && pip install .[ray] ray==2.0.1
> ```

Isn't this particular command line was used previously for ray backend specifically? I recall @dchigarev did something like this

**Comment by dchigarev** [comment]
> > It turns out
> > ```
> >  cd modin && pip install -e . && pip install .[ray] ray==2.0.1
> > ```
> 
> Isn't this particular command line was used previously for ray backend specifically? I recall @dchigarev did something like this

I don't quite understand the source of the line that you're referencing. The only thing I recall somehow related to this is our steps in CI that run modin's benchmarks (taxi, plasticc, ...).

Here's the line we used to setup modin-on-ray environment, here we install modin with no engine specified and then separately install the latest ray:
```
# Modin installation
cd modin && pip install -e . && pip install ray && pip install psutil && cd ..
```
We did it in a separate conda environment (there were two envs: modin_on_hdk and modin_on_ray), so this shouldn't have affected HDK's env anyhow.
